slct = {"doom":         {"ostypes": ["osx"],
                         "paths"  : [{"source" : {"osx"  : "$AB_DLZ_DOTFILES/.doom.d"},
                                      "target" : {"osx"  : "$HOME/.doom.d"}}]},
        "feh":          {"ostypes": ["arch"],
                         "paths"  : [{"source" : {"all"  : "$AB_DLZ_DOTFILES/.fehbg"},
                                      "target" : {"arch" : "$HOME/.fehbg"}}]},
        "jrnl":         {"ostypes": [],
                         "paths"  : [{"source" : {"osx"  : "$AB_DLZ_DOTFILES/jrnl"},
                                      "target" : {"osx"  : "$HOME/.config/jrnl"}}]},
        "newsboat":     {"ostypes": [],
                         "paths"  : [{"source" : {"all"  : "$AB_DLZ_DOTFILES/.newsboat/config"},
                                      "target" : {"osx"  : "$HOME/.newsboat/config"}},
                                     {"source" : {"all"  : "$AB_DLZ_DOTFILES/.newsboat/urls"},
                                      "target" : {"osx"  : "$HOME/.newsboat/urls"}}]},
        "ranger":       {"ostypes": [],
                         "paths"  : [{"source" : {"all"  : "$AB_DLZ_DOTFILES/rc.conf"},
                                      "target" : {"all"  : "$HOME/.config/ranger/rc.conf"}}]},
        "sc-im":       {"ostypes":  [],
                         "paths"  : [{"source" : {"all"  : "$AB_DLZ_DOTFILES/sc-im"},
                                      "target" : {"all"  : "$HOME/.config/sc-im"}}]},
        "sxhkd":        {"ostypes": ["arch"],
                         "paths"  : [{"source" : {"arch"  : "$AB_DLZ_DOTFILES/sxhkd"},
                                      "target" : {"arch"  : "$HOME/.config/sxhkd"}}]},
        "systemd":      {"ostypes": ["arch"],
                         "paths"  : [{"source" : {"arch"  : "$AB_DLZ_DOTFILES/systemd"},
                                      "target" : {"arch"  : "$HOME/.config/systemd"}}]},
        "taskwarrior":  {"ostypes": [],
                         "paths"  : [{"source" : {"osx"  : "$AB_DLZ_DOTFILES/.taskrc"},
                                      "target" : {"osx"  : "$HOME/.taskrc"}}]},
        "taskopen":     {"ostypes": [],
                         "paths"  : [{"source" : {"all"  : "$AB_DLZ_DOTFILES/.taskopenrc"},
                                      "target" : {"all"  : "$HOME/.taskopenrc"}}]},
        "timewarrior":  {"ostypes": [],
                         "paths"  : [{"source" : {"osx"  : "$AB_WIKI_DIR/.timewarrior"},
                                      "target" : {"osx"  : "$HOME/.timewarrior"}}]},
        "tig":          {"ostypes": [],
                         "paths"  : [{"source" : {"osx"  : "$AB_DLZ_DOTFILES/tig"},
                                      "target" : {"osx"  : "$HOME/.config/tig"}}]},
        "todo.txt":     {"ostypes": ["osx"],
                         "paths"  : [{"source" : {"all"  : "$AB_DLZ_DOTFILES/todo.txt/.todo.cfg"},
                                      "target" : {"osx" : "$HOME/.todo.cfg"}}]},
        "vit":          {"ostypes": [],
                         "paths"  : [{"source" : {"all"  : "$AB_DLZ_DOTFILES/.vit"},
                                      "target" : {"all" : "$HOME/.vit"}}]},
        "vscode":       {"ostypes": [],
                         "paths"  : [{"source" : {"osx" : "$AB_DLZ_DOTFILES/vscode/settings.json"},
                                      "target" : {"osx" : "$HOME/Library/Application Support/Code/User/settings.json"}},
                                     {"source" : {"osx" : "$AB_DLZ_DOTFILES/vscode/keybidings.json"},
                                      "target" : {"osx" : "$HOME/Library/Application Support/Code/User/keybidings.json"}}]},
        "xinit":        {"ostypes": ["arch"],
                         "paths"  : [{"source" : {"all"  : "$AB_DLZ_DOTFILES/.xinitrc"},
                                      "target" : {"arch" : "$HOME/.xinitrc"}}]},
        }
